### ISSUE TITLE
Fix Docker Build Process

### ISSUE THREAD

**Issue by mondele** [Bible-Translation-Tools/BTT-Writer-Desktop#121]
As a developer, I want to be able to speed the test cycle by using the `make build` and `make run` features of the docker container. However, these features don't generally work, currently. As a result, I have to `make release`, which only makes a Linux release. Some of our partners would like to develop on Windows as well.

**Comment by PurpleGuitar** [comment]
Max, this one's a little tricky, and requires playing around with Docker.  As John reported, for a long time we've been able to build and run BTT-Writer on Linux by using `make build` to create a Docker image with the latest code, and then `make run` to create and run a container.  The container uses the local X server to create the window and allow you to interact with the app.

But a year or so ago, it all stopped working and we're not sure why.  Perhaps it has something to do with Electron, or X/Wayland, or something else.  Would you please investigate and see if it's possible to get it working again?
