### ISSUE TITLE
RTL flag seems to be wrong for Arabic

### ISSUE THREAD

**Issue by PurpleGuitar** [Bible-Translation-Tools/BTT-Writer-Desktop#122]
From Chuck Liesch, 2023-05-05:

While assisting the Garme people last week, we were using the AVD as a source text.   It appears the formatting is not rendered correctly in BTT-W.   V1 and v3 of these two chunks are each located on the left side, as if it was a LTR language.   AVD is rendered correctly on BIEL Read on Web  NAV has the same formatting issue on BTT-W as well.

It's identified as LTR in the package.json  {​​​​​​​  "package_version": "0.1",   "modified_at": 20220324,   "content_mime_type": "text/usx",   "language": {​​​​​​​     "slug": "arb",     "name": "العربية",     "direction": "ltr"   }​​​​​​​,

**Comment by mondele** [comment]
I can confirm:
Updating source texts does not revert the text direction to LTR if the change is made locally and manually to RTL in the index.sqlite.

Further, downloading a new copy of the AVD source for a particular book (although the existing source is up-to-date) does not revert the text direction, either.

**Comment by mondele** [comment]
Fresh install of BTT-Writer:

1. Language `ar` is present in sources, for Arabic. Language is RTL.
2. Language `arb` is not present in source languages.

After update of list of source languages:

1. Language `arb` has been added for AVD and NAV sources.
2. Direction is LTR.

So, yes, one of our upstream sources is corrupt — this doesn't appear to be an installation issue.

**Comment by mondele** [comment]
Updating `index.sqlite` in `src/index` with the addition of `arb` in the source table propagates through build.

1. Language `ar` is present in sources, for Arabic. Language is RTL.
2. Language `arb` is present in sources, for Arabic. Language is RTL.

After update of list of source languages:

1. Language `arb` has been changed from RTL to LTR.

**Comment by mondele** [comment]
It looks like this issue can be closed, since it was actually a pipeline issue.
