### ISSUE TITLE
Missing Verse in Isaiah 6

### ISSUE THREAD

**Issue by ChrisJarka** [Bible-Translation-Tools/BTT-Writer-Desktop#14]
In version 1.0.5 Build 5 - shows as Version 1.0(Build 5) in the program - Isaiah 6 is missing a place to add verse 11 marker.

![ISA 6 11 missing Version1 0Build5](https://user-images.githubusercontent.com/9850185/94431974-0d835400-0164-11eb-89a3-508e7b2ebd60.png)

According to the USFM file - lines 555-578 - the \v markers for verses 11&12 are correctly placed between two \s5 markers. 
\s5
\p
\v 8 I heard the voice of the Lord say, "Whom will I send; who will go for us?" Then I said, "Here I am; send me."
\q1
\v 9 He said, "Go and tell this people,
\q1 'Hearing you will hear, but you do not understand; you keep on seeing, but you do not know.'

\s5
\v 10 Make the heart of this people insensitive, and their ears dull, and blind their eyes.
\q1 Otherwise they might see with their eyes, hear with their ears, and understand with their heart, and then turn and be healed."

\s5
\p
\v 11 Then I said, "Lord, how long?" He answered,
\q1 "Until cities crash into ruins and are without inhabitants,
\q1 and the houses are without people, and the land falls into a desolate waste,
\q1
\v 12 and until Yahweh has sent the people far away, and the whole land is completely abandoned.

\s5
\q1
\v 13 Even if a tenth of the people remain in it, it will again be destroyed;
\q1 as a terebinth or an oak is cut down and whose trunk remains,
\q1 the holy seed is in its stump."

**Comment by AnonymousWalker** [comment]
@ChrisJarka can you tell which os was the app installed to?

**Comment by AnonymousWalker** [comment]
@ChrisJarka the typo issue on WACS https://content.bibletranslationtools.org/WA-Catalog/en_ulb/issues/3 
probably affected the verse marker, since writer gets the source text from that repo.
