### ISSUE TITLE
Enhancement request: Backup project before deletion

### ISSUE THREAD

**Issue by mondele** [Bible-Translation-Tools/BTT-Writer-Desktop#143]
v1.2.3

As a user, I would like BTT-Writer to back up a project before it is deleted. This could be done to the existing **automatic_backups** folder. Additionally, if the project can not be made into a tstudio file because of an error, it should be simply zipped for safekeeping, again probably to the **automatic_backups** folder.

**Comment by PurpleGuitar** [comment]
Max, would you please take a look at this?  Perhaps we can kick off a backup and wait for it to finish during the delete workflow.
