### ISSUE TITLE
Link for end user to view uploaded work

### ISSUE THREAD

**Issue by PurpleGuitar** [Bible-Translation-Tools/BTT-Writer-Desktop#16]
[2/5 9:16 AM] Christine Jarka

Link for end user to view uploaded work
    
As an end user I would like to see the "human readable" translated content on read.bibletranslationtools.org rather than be taken to the repo of what I've uploaded.
Yes, as an end-user I can click on the 'Read on Web' button at the top of the git/repo window, but I need to know that is what I need to do to see my work.

![image](https://user-images.githubusercontent.com/1095575/107664139-1b8cc980-6c5a-11eb-99f6-536e747f6bfe.png)

**Comment by AnonymousWalker** [comment]
@PurpleGuitar should we replace that link with 
`http://read.bibletranslationtools.org/u/clash/bn_mat_text_ulb` ?

which basically swaps the prefix of that url

**Comment by PurpleGuitar** [comment]
Confirmed.  Will be in the next release.
