### ISSUE TITLE
change name of token in WACS profile settings

### ISSUE THREAD

**Issue by ChrisJarka** [Bible-Translation-Tools/BTT-Writer-Desktop#17]
As an end-user of BTT Writer I would be looking for a token for the Writer program and not the ts program.

![tokens named ts](https://user-images.githubusercontent.com/9850185/108724706-a17b0100-74f3-11eb-8f8d-0cb3c78ecc7d.PNG)

Could the token name be changed to reflect the BTT Writer program?

**Comment by mondele** [comment]
Since ideally we will resolve the token "corruption" issue, and end-users won't need to manually delete their tokens, I'm not sure this is an abiding issue.
