### ISSUE TITLE
Git is not installed. It is required to run tStudio Desktop.

### ISSUE THREAD

**Issue by monchotech** [Bible-Translation-Tools/BTT-Writer-Desktop#23]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check that you are using the [latest version](https://github.com/unfoldingWord-dev/ts-desktop/releases/latest) of the app.
- [x] Check that a similar issue has not already been opened.

I get this notification installing in MAC Book Pro 16 inc, 2019. macOS Big Sur version 11.2.3

**_"Git is not installed. It is required to run tStudio Desktop."_**

What I have to do to fix this issue in my Mac?

MoNcHo

**Comment by mondele** [comment]
Open the Terminal application.
Type `xcode-select --install`
Press return.
You will be prompted to install the command line developer tools. (These are different for each version of MacOS, and we are not permitted to distribute them.)
After the installation, you should be able to run BTT-Writer with no further difficulties.
