### ISSUE TITLE
BTT Writer setup - bundled git client check has confusing wording  

### ISSUE THREAD

**Issue by sea-liesch** [Bible-Translation-Tools/BTT-Writer-Desktop#36]
During setup when BTT-Writer starts to install the git client, it does a version check and returns a slightly confusing message:

"Git for Windows 2.27.0 is currently installed.  Do you really want to **downgrade** to Git for Windows 2.9.2?"

**Comment by 16dprice** [comment]
@sea-liesch 
What exactly is confusing about it?

I see that you bolded the word "downgrade" there, but 2.9.2 is a downgrade from 2.27.0. Is the confusion that it wants to change your git version at all?

**Comment by sea-liesch** [comment]
I read it wrong.   I thought it said 2.2.7
