### ISSUE TITLE
Unknown Error The project information is corrupt when trying to create translationWords project

### ISSUE THREAD

**Issue by sea-liesch** [Bible-Translation-Tools/BTT-Writer-Desktop#48]
Mac OS x Big Sur 11.2.3  Clean install of BTT -Writer App Version
1.1 (Build 6)

log.txt
2021-05-19 11:43:56 I/ts-dashboard.html.js:1114:3: 
	Git Version 2.14.1
2021-05-19 11:43:56 I/migrator.js:31:2: Migrated projects
	[]
2021-05-19 11:44:0 I/ts-dashboard.html.js:1114:3: 
	Git Version 2.14.1
2021-05-19 11:55:42 I/ts-dashboard.html.js:1114:3: 
	Git Version 2.14.1
2021-05-19 11:56:32 E/projects.js:274:26: 
	TypeError: Cannot read property 'language_id' of undefined
2021-05-19 11:58:40 E/projects.js:274:26: 
	TypeError: Cannot read property 'language_id' of undefined

**Comment by sea-liesch** [comment]
Confirmed same behavior on Microsoft Windows [Version 10.0.19042.985]  and BTT Writer App Version
1.1 (Build 6)

"Unknown Error
The project information is corrupt" when trying to create translationWords project. 
last two entries in log.txt:

	
2021-05-19 12:18:47 I/ts-dashboard.html.js:1114:3: 
	Git Version 2.9.2.windows.1
2021-05-19 12:18:52 E/projects.js:274:26: 
	TypeError: Cannot read property 'language_id' of undefined

**Comment by sea-liesch** [comment]
Confirmed same behavior on Linux Mint (Ubuntu 20.04)  20 Cinnamon 4.6.7 UI   
BTT-Writer version BTT-Writer-1.1.0-6-linux-x64.zip

log.txt 
~snip~

2021-05-19 15:26:39 I/ts-dashboard.html.js:1114:3: 
	Git Version 2.25.1
2021-05-19 15:27:30 E/projects.js:274:26: 
	TypeError: Cannot read property 'language_id' of undefined

**Comment by AnonymousWalker** [comment]
@sea-liesch can you provide the steps/actions that caused the error?

**Comment by sea-liesch** [comment]
From the BTT-Writer home, start  a new project.    Choose target language.  I used both english demo1 and english demo2 as target projects.   Once a target language is selected, you are prompted to choose a category.  Select "Other"  Choose a project screen opens with the only option is "translationWords"  Once I click on translationWord  I get the error: "Unknown Error The project information is corrupt"
