### ISSUE TITLE
Unable to Create a Server Account on BTT-Writer-Desktop*

### ISSUE THREAD

**Issue by mondele** [Bible-Translation-Tools/BTT-Writer-Desktop#68]
When a user tries to create a server account using BTT-Writer-Desktop, the process appears to fail.
![image](https://user-images.githubusercontent.com/25468552/149528315-880e7791-f129-439d-9d55-435978cc399f.png)
Sometimes, account creation has indeed failed. I suspect in these cases it's because the password doesn't meet requirements, although these are not shown anywhere in the app.

However, even if the account is created, the Creation Failed message is displayed. This can cause some understandable confusion. (Especially if the user then tries to create the account _again_, and is told that an account for that username and/or email address already exists.

Additionally, even if the account is created, the user is still unable to log in using BTT-Writer. WACS seems to be configured to require a password change on initial login by default. This is not doable in BTT-Writer, so the user is still unable to log in without using the web site.

**Comment by mondele** [comment]
I have an unfortunate update to this! There is also a text "CREATE A NEW ACCOUNT" button on the Server Login screen. This button also needs to redirect to the server account creation page...

**Comment by PurpleGuitar** [comment]
Fix merged, will be released soon.
