### ISSUE TITLE
BTT-Writer hangs when "Cancel" is pressed instead of importing project file

### ISSUE THREAD

**Issue by mondele** [Bible-Translation-Tools/BTT-Writer-Desktop#78]
When using **Import Project File**, if the user clicks **Cancel** in the file picker, the program hangs on the **Importing. Please wait…** throbber.

Errors from the console:
`internal/validators.js:124 Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124)
    at Object.basename (path.js:1156)
    at Object.extractBackup (/opt/BTT-Writer/reso…c/js/importer.js:18)
    at ts-dashboard.html.js:423
/opt/BTT-Writer/reso…/sql.js/js/sql.js:3 Uncaught TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124)
    at Object.basename (path.js:1156)
    at Object.extractBackup (/opt/BTT-Writer/reso…c/js/importer.js:18)
    at ts-dashboard.html.js:423`

**Comment by PurpleGuitar** [comment]
Confirmed.  Reproduction steps:

- Open BTT-Writer.
- Log in if needed.
- Click the three-dot menu, then click "Import".
- Click Import Project File.
- From the "Open" dialog, click the "Cancel" button.
- Observe that BTT-Writer hangs.
- In the developer console (Ctrl-Shift-i), observe that there is an uncaught error.

I guess there's a check missing in the import button handler -- probably it should check the returned path and abort the action if it's null.

**Comment by mondele** [comment]
This is fixed in release 1.1.7
